language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=7.2
    - PHP72=7.2.3
    - PHP71=7.1.15
  matrix:
    - TAG=7.2 PHP_VER="${PHP72}" EXTRA_TAG=7
    - TAG=7.1 PHP_VER="${PHP71}"
    - TAG=7.2-dev PHP_VER="${PHP72}" PHP_DEV=1 EXTRA_TAG=7-dev
    - TAG=7.1-dev PHP_VER="${PHP71}" PHP_DEV=1
    - TAG=7.2-dev-macos PHP_VER="${PHP72}" PHP_DEV=1 WODBY_USER_ID=501 WODBY_GROUP_ID=20 EXTRA_TAG=7-dev-macos
    - TAG=7.1-dev-macos PHP_VER="${PHP71}" PHP_DEV=1 WODBY_USER_ID=501 WODBY_GROUP_ID=20
    - TAG=7.2-debug PHP_VER="${PHP72}" PHP_DEBUG=1 EXTRA_TAG=7-debug
    - TAG=7.1-debug PHP_VER="${PHP71}" PHP_DEBUG=1

script:
  - set -e
  - cd "${PHP_VER:0:1}" || cd "${PHP_VER:0:3}"
  - make compare-orig-configs
  - travis_retry make
  - make test

after_success:
  - bash "${TRAVIS_BUILD_DIR}/travis_release"
